name: novo_projeto
description: "Um aplicativo de rádio simples com reprodução em segundo plano."
publish_to: 'none'
version: 0.2.0+2

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Pacotes para áudio em segundo plano
  audio_service: ^0.18.12
  just_audio: ^0.9.36
  audio_session: ^0.1.18

  # Persistência de dados simples para a última rádio ouvida
  shared_preferences: ^2.2.3

  # Pacotes para permissões e info
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0

  # Pacotes para a interface
  cached_network_image: ^3.3.1 
  glassmorphism: ^3.0.0
  palette_generator: ^0.3.3+3

  # >>> ADICIONADO PARA REQUISIÇÕES HTTP <<<
  http: ^1.2.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
